skvadrik/re2c

re2c/doc/manpage.rst.in, re2c/src/conf/msg.cc
While working to update the re2c package in debian, the package checker (lintian) complained about a bunch of [common](https://lintian.debian.org/tags/spelling-error-in-manpage.html) [misspellings](https://lintian.debian.org/tags/spelling-error-in-binary.html) in the manpage and --help text. Nothing urgent, but since I was patching them on the debian end anyway I figured it couldn't hurt to create a pull request here as well.
=> typo fixes for manpage and --help text

re2c/src/codegen/bitmap.h, re2c/src/codegen/go.h, re2c/src/ir/adfa/action.h, re2c/src/ir/nfa/nfa.h
structs State and OutputFile forward declared as class.
classes Range, RegExp and RuleOp forward declared as struct.
Fixed forward declarations.
=> Fix #158 Inconsistent forward declaration of struct/class vs definition

re2c/src/codegen/output.cc
Text files need to be opened for writing with "w", so that stdio does
the right thing in respect to the correct line endings for the current OS.
("\r\n" in Windows, "\n" in Linux).
=> Fix #160 - Open text files with "wb" causes issues on Windows

re2c/Makefile.am
In some situations src/parse/ may not exist before a file is copied into the
directory. Ensure that this doesn't happen by creating the directory first.
=> Makefile.am: create target directory before writing into it

re2c/src/dfa/dfa.h
On g++-3.4.6 re2c tests SIGSEGVed due to use of uninitialized data:
```
$ valgrind ... ./re2c -8 a.re -o foo.c
Conditional jump or move depends on uninitialised value(s)
at 0x432F23: re2c::tcpool_t::insert(re2c::tcmd_t const*) (tcmd.cc:202)
by 0x421FDA: re2c::freeze_tags(re2c::dfa_t&) (freeze.cc:45)
by 0x43A7FF: re2c::ast_to_dfa(re2c::spec_t const&, re2c::Output&) (compile.cc:88)
by 0x43B052: push_back (stl_iterator.h:614)
by 0x43B052: re2c::compile(re2c::Scanner&, re2c::Output&, re2c::Opt&) (???:0)
by 0x449D29: main (main.cc:31)
Uninitialised value was created by a heap allocation
at 0x403252F: operator new[](unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x42FC9E: re2c::find_state(re2c::determ_context_t&) (dfa.h:37)
by 0x429BD9: …
```
=> src/dfa/dfa.h: simplify constructor to avoid g++-3.4 bug

re2c/configure.ac
`xz` compresses twice as good as `gzip` on `re2c` sources:
```
$ ls -lh *1.1.1*
4,8M re2c-1.1.1.tar.gz
2,5M re2c-1.1.1.tar.xz
```
Switch `make dist` to `xz by default. `gzip` is still available
via `make dist-gzip`.
Reported-by: rofl0r
Bug: https://github.com/skvadrik/re2c/issues/221
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
=> configure.ac: enable xz tarballs instead of gzip by default

Makefile.am
This is important when re2c is packaged in distributions, so that one can
quickly check what license the re2c is distributed under. Distributions
typically use the release tarball, not the git repository, and so this commit
puts the LICENSE file into the release tarball also.
=> Package LICENSE file in the release tarball

configure.ac
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) we noticed that `re2c` could not be built reproducibly. This is because it used the current build date in the manual page and was originally filed in Debian as [#934697](https://bugs.debian.org/934697).
This patch uses the [SOURCE_DATE_EPOCH environment variable](https://reproducible-builds.org/specs/source-date-epoch/).
=> Make the build reproducible

.travis.yml
I'm not sure what would be the actual benefit. Let's try it in action!
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
=> .travis.yml: enable ccache to speed up incremental builds

configure.ac
This makes root directory less cluttered. Autoconf-specific
scripts like 'config.guess'. 'install-sh' and friends
are moved to build-aux/ now.
=> configure.ac: store auxiliary configure files in build-aux/

autogen.sh
On a fresh checkout `autogen.sh` complains about missing `m4`:
```
$ ./autogen.sh
aclocal-1.16: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
...
```
The change always attempts to create the directory.
=> autogen.sh: always attempt to create m4/ directory

src/dfa/closure_posix.h
Hi, I'm the MacPorts maintainer of re2c. We discussed a problem a few years ago in #198 where old versions of gcc were unable to compile your code, and you committed a simple fix but warned that it might break in the future.
It did, and we received a couple reports about it. It was reported last year that [re2c 1.2.1 didn't build with gcc 4.2](https://trac.macports.org/ticket/58993) on Mac OS X 10.4 on PowerPC:
```
./src/dfa/closure_posix.h:128: error: no match for 'operator!=' in 'c != std::vector<_Tp, _Alloc>::rend() [with _Tp = re2c::clos_t, _Alloc = std::allocator<re2c::clos_t>]()'
```
I had forgotten about our previous discussion and worked around the problem by using a newer compiler, but then it was reported a few days ago that [re2c 1.3 didn't build with clang …
=> Fix for old compilers like gcc 4.2 and clang 3.4

CMakeLists.txt
Fix build in environment where CMake is not in path.
=> Fix CMake command from cmake to ${CMAKE_COMMAND}

src/encoding/utf8/utf8.cc, test/encodings/utf8_literals.c, test/encodings/utf8_literals.re
Masked a character with a bit at 0x0F0000 position with MAX_4BYTE_RUNE (0x10FFFF) that bit was missing.
Such as 𤰖 (0x024C16).
=> Fix UTF-8 decode for 4bytes rune

.github/workflows/ci.yml
Hello,
This PR introduces initial GitHub Actions support by adding Configure, Build and Test steps. Right now it uses only Linux. I'll add macOS and Windows support a bit later.
To see how it works now refer to: https://github.com/sergeyklay/re2c/runs/1175055832?check_suite_focus=true
=> Initial support of CI using GitHub Actions

.github/workflows/ci.yml
Hello,
This PR adds macOS with Apple Clang to the build matrix on GitHub Action. I'd prefer not to complicate the workflow configuration at this time until I have a complete matrix.
To see how it works now refer to: https://github.com/sergeyklay/re2c/actions/runs/282978499
=> Add macOS support for GitHub Actions

.github/workflows/ci.yml, CMakeLists.txt
Hello,
This PR adds Windows  with Visual Studio 16 2019 to the build matrix on GitHub Action. There still a lot of work, e.g. provide ability to run tests, compiler flags definition and so on. But right now it works. I'll try to improve Windows builds a bit later.
=> Add Windows support for GitHub Actions

CMakeLists.txt
This PR fixes my previous PR (#311) to use platform independent bison search.
After discussion in https://github.com/skvadrik/re2c/pull/311#discussion_r498687041, I decided to double-check this approach again and made sure that it actually works.  I don't quite understand why I wasn't able to get this to work before, maybe I didn't read the documentation carefully or missed something important. Anyway now it works, and looks clear and simple as initially.
To see how it works refer https://github.com/sergeyklay/re2c/runs/1198167217?check_suite_focus=true#step:8:16
=> Cleaned up CMakeLists.txt to use platform independent bison search

.github/workflows/ci.yml
Hello,
This PR amends build matrix by adding Release configuration. There are no compiler flags changes yet because I still trying to choice a better way to set flags for various compilers.
=> Add Release build type to the build matrix

.github/workflows/ci.yml, cmake/Re2cCompilerFlags.cmake
Hello,
This PR amends the build matrix on GitHub Actions. The full used matrix is:
|  OS | Build Type  | Build Dir  | Common Flags | Skeleton |
| :---  |  ---  | --- | --- | --- |
| Linux | `Debug` | out-of-tree | `-O2 -fsanitize=undefined` | false |
| Linux | `Debug` | out-of-tree | `-O2 -fsanitize=address` | false |
| Linux | `Debug` | out-of-tree | `-O2` | false |
| Linux | `Debug` | in-tree | `-O2` | false |
| Linux | `Debug` | out-of-tree | `-O2` | **true** |
| Linux | `Release` | out-of-tree | — | false |
| macOs | `Debug` | out-of-tree | `-O2` | false  |
| macOs | `Debug` | out-of-tree | `-O2` | **true** |
| macOs | `Debug` |  in-tree | `-O2` | false  |
| macOs | `Release` | out-of-tree | — | false  |
| Windows | `Debug` | out-of-tree | — | false |
| Windows | `Debug` | in-tree | — …
=> GitHub actions improvements

.github/workflows/ci.yml, build/__cmakebuild_asan.sh, build/__cmakebuild_ubsan.sh, cmake/Re2cBuildType.cmake, cmake/Re2cCompilerFlags.cmake
Hello,
This PR adds support of Asan and Ubsan build types for CMake. I prefer this option since it expresses the intent (run sanitizers) rather than modifies a number of flags. This also simplifies a bit build matrix on GitHub workflow.
Usage:
```bash
$ cmake \
-DCMAKE_BUILD_TYPE=Asan \
...
...
```
Old school fans can still use the way with explicit passing of flags:
```bash
$ cmake \
-DCMAKE_C_FLAGS="-g -fsanitize=address -fno-omit-frame-pointer" \
-DCMAKE_CXX_FLAGS="-g -fsanitize=address -fno-omit-frame-pointer" \
-DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" \
-DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=address" \
...
...
```
Note, I added `-fno-omit-frame-pointer` to Asan build type and do not added `-O2` (it is added by workflow matrix). Let me know if you'd like to modify Asan/Ubsan …
=> Added Asan and Ubsan CMake profiles

.github/workflows/ci.yml, CMakeLists.txt
This PR adds ability to install re2c as well as re2go on GitHub Actions.
Another notable changes are:
I've started work to enable `install` targets for Windows. There is no ability to install libs yet, but the main binaries can be already installed.
Renamed `Minimal Load Test (Windows)` job to more generic  `Minimal Install Test`. We'll amend this job in the future. But right now it tests that after installation the necessary binaries are in the expected place and you can run them (on Windows too).
Make the names of the builds more descriptive as discussed here:  https://github.com/skvadrik/re2c/pull/317#issuecomment-706685657
=> Add minimal install test on GitHub Actions

cmake/Re2cBootstrapLexer.cmake
Fixes the following build scenario:
$ mkdir stage1 && cd stage1
$ cmake .. && make
$ cd .. && mkdir stage2 && cd stage2
$ cmake .. \
-DRE2C_REBUILD_LEXERS=yes \
-DRE2C_FOR_BUILD=$(pwd)/../stage1/re2c && make
=> Create output directories for CMake builds with RE2C_REBUILD_LEXERS=yes.

CMakeLists.txt, build/gen_help.sh, cmake/Re2cGenDocs.cmake
**Add the ability to generate manpage and documentation for BSD systems**
- Stripping headers may not work as expected, as man output differs on different systems. This should work now.
- Simplified output parsing procedure by replacing the regular expression by `TERM=dumb`.
- Stripping escape sequences.
- Added documentation about the intentions of this script.
**Check for `man` and `sed` on Windows when `RE2C_REBUILD_DOCS` is `ON`**
Windows does not have a native `man` and `sed` commands. Therefore, we are looking for the Cygwin versions of  `man` and `sed`. This doesn't add full Windows support. However, in case of the absence of the required programs, this shows error messages before the build stage.
**Rephrase error messages for `RE2C_REBUILD_DOCS=ON`**
This aims to provide a bit …
=> Add the ability to generate manpage and documentation for BSD systems

.github/workflows/ci.yml
This is a planned, intermediate change that prepares the following things:
- Preparing to use different generators (Xcode, NMake, Ninja)
- Preparing to use rebuild and test documentation (thanks to https://github.com/skvadrik/re2c/pull/326). This required renaming some steps
- Preparing to build libs
- Preparing to use Autotools
- Preparing to make a full migration of CMake builds from Travis CI
Notable improvements include the unification of the Configure job (now it is Fast Configure) for all platforms
=> Restructuring Configure and Build jobs on GitHub Actions

.github/workflows/ci.yml
This PR adds ability to build re2c on GitHub Actions with the following options:
- **`-DRE2C_REBUILD_LEXERS=ON`**: Windows, macOs, Linux
- **`-DRE2C_BUILD_LIBS=ON`**: Windows, macOs, Linux
- **`-DRE2C_REBUILD_DOCS=ON`**: macOs, Linux
With this PR I completely implement CI on GitHub Actions using CMake. Current workflow configuration fully cover the Travis' configuration (even more).
=> Complete CI implementation using CMake and GitHub  Actions

src/skeleton/generate_data.cc
At least on ext4 `open(O_TRUNC); write(); close()` works a lot
slower than `unlink(); open(); write(); close()`.
My speculation is that ext4 has to do non-trivial free block
accounting at `close()` time that were freed by `O_TRUNC`.
Before the patch:
```
$ rm 1.c.line8.input 1.c.line8.keys; time ../re2c bug128.re -o 1.c -Si
real    0m3,011s
user    0m2,091s
sys     0m0,907s
$ time ../re2c bug128.re -o 1.c -Si
real    0m9,506s
user    0m1,708s
sys     0m0,946s
```
After the patch:
```
$ rm 1.c.line8.input 1.c.line8.keys;  time ../re2c bug128.re -o 1.c -Si
real    0m3,785s
user    0m2,615s
sys     0m1,152s
$ time ../re2c bug128.re -o 1.c -Si
real    0m3,570s
user    0m2,348s
sys     0m1,205s
```
It's a 3x speedup.
=> skeleton: delete '.input' and '.keys' files before overwriting them

libre2c_old/examples/compare/compare.h
There is a small typo in libre2c_old/examples/compare/compare.h.
Should read `otherwise` rather than `otheriwse`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, otheriwse -> otherwise

src/compile.cc
Hi,
By trying to build re2c on Windows, using MSVS 2017 I faced the compile-time error: C2039: 'isalnum': is not a member of 'std'. This PR fixes this issue.
By the way I added a small fix of using this function: in order to avoid UB (which may occur in some situations, see links below) the argument should be passed by preliminary converting it to unsigned char. More info about this issue:
-  https://stackoverflow.com/a/39520176/1117306
-  https://en.cppreference.com/w/cpp/string/byte/isalnum.
=> Fix compiling on Windows (MSVC)

cmake/Re2cCompilerFlags.cmake
HI,
By looking at build log on Windows (MSVC) I noticed a number of warnings of the form:
`'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc (compiling source file ...src\codegen\gen_state.cc)`
If I recall correctly from my experience, if this flag isn't set then we may encounter situations when destructors of automatic objects aren't called during the exception propagation process. 
The following doc also recommends (if project doesn't use SEH) to set this flag:
https://docs.microsoft.com/ru-ru/cpp/build/reference/eh-exception-handling-model?view=msvc-160
=> Enable support of C++ exceptions on MSVC builds.

configure.ac
In https://bugs.gentoo.org/779187 Matt noticed errors when running ./configure
on dash:
./configure: 5339: test: x: unexpected operator
./configure: 5386: test: x: unexpected operator
The change is to use POSIX '=' comparison instead of bash-specific ==.
Patch-by: Matt Whitlock
Bug: https://bugs.gentoo.org/779187
=> configure.ac: avoid bash-specific '==' comparison

run_tests.py.in
The previous version of this function has multiple responsibilities and actually had knowledge for which it was not intended.
These changes are about "S" in SOLID.
P.S.  This should also speed up a bit  the test run, since now, in few places, we don't do additional FS scans.
=> Make remove() function simpler

CMakeLists.txt, configure.ac, run_tests.py.in
Useful on systems with multiple python implementations.
While at it allow both 'python3' (preferred) and 'python' spellings.
=> configure.ac: allow user to set non-standard PYTHON

src/util/temp_file.cc
This fixes the error:
error: ‘fdopen’ was not declared in this scope; did you mean ‘fopen’?
=> Define _POSIX_SOURCE for fdopen in cygwin

.github/workflows/benchmarks.yml
Use `actions/setup-java` instead of `actions/setup-python` for the `Setup Java` step in the benchmarks workflow. Something seemed off about the action that was currently being used for setting up Java.
=> Setup Java for the benchmarks workflow using actions/setup-java

src/codegen/code.h, src/options/symtab.h, src/regexp/re.h
Detected by clang's-Weverything:
./src/regexp/re.h:17:1: warning: struct 'Msg' was previously declared as a class;
this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct Msg;
^
=> fix struct/class declaration mismatch (-Wmismatched-tags)

src/parse/ast.h, src/util/free_list.h
clang with -Weverything detects these as:
./src/util/free_list.h:9:16:
warning: identifier '_Ty' is reserved
because it starts with '_' followed by a capital letter [-Wreserved-identifier]
template<class _Ty>
^
=> avoid using reserved identifiers (underscores)

CMakePresets.json, cmake/Re2cGenDocs.cmake
Otherwise variable definitions from "fast" configuration take precedence
over the "full" configuration, resulting in disabling some important
configrations, such as Go language support.
For example, if "fast" is inherited before "full" we have the following
incorrect configrations that sets RE2C_BUILD_RE2GO:BOOL="FALSE":
$ cmake -S .. --preset=linux-gcc-release-ootree-skeleton-full
Preset CMake variables:
CMAKE_BUILD_TYPE="Release"
CMAKE_CXX_COMPILER="g++"
CMAKE_C_COMPILER="gcc"
CMAKE_INSTALL_PREFIX:PATH="[CUT]/re2c/install"
RE2C_BUILD_LIBS:BOOL="TRUE"
RE2C_BUILD_RE2GO:BOOL="FALSE"
RE2C_FOR_BUILD="[CUT]/re2c/install/bin/re2c"
RE2C_REBUILD_DOCS:BOOL="TRUE"
RE2C_REBUILD_LEXERS:BOOL="TRUE"
But if "full" is inherited after "fast" we have the following (correct):
$ cmake -S .. …
=> CMakePresets.json: inherit "full" configuration before "fast".

.github/workflows/ci.yml
CI runs occasionally fail to fetch apt packages due to unavailable
remote. Let's try to cache heavyweight .deb packages and see if it
helps.
.deb files should not normally change frequently.
=> .github/workflows/ci.yml: set up trivial apt cache

.github/workflows/ci-cmake.yml
A prerequisite for basic autotools-based build.
=> .github/workflows: rename ci.yml to ci-cmake.yml

.github/workflows/ci-autotools.yml, Makefile.am, cmake/Re2cBootstrapParser.cmake, src/parse/parser.ypp
The change allows catching fresh bison diagnostics. Current example:
GEN      src/parse/parser.cc
src/parse/parser.ypp:60.2: warning: empty rule without %empty [-Wempty-rule]
60 | : /* empty */
|  ^
|  %empty
%empty was introduced in bison-2.7.90 around 2013.
=> Enable bison warnings

cmake/Re2cBootstrapParser.cmake
Autotools-based and cmake-based build systems had slightly different flag order:
Makefile.am:    $(AM_V_GEN)$(BISON) --warnings --output=$@ --defines=$(@:cc=h) $<
Let's make them identical.
=> cmake/Re2cBootstrapParser.cmake: change flag order to match Makefile.am

bootstrap/lib/lex.cc, bootstrap/lib/parse.cc, bootstrap/lib/parse.h, bootstrap/src/parse/lex.cc, bootstrap/src/parse/parser.cc, bootstrap/src/parse/parser.h, lib/lex.h, lib/lex.re, lib/parse.ypp, lib/regcomp.cc, src/parse/lex.re, src/parse/parser.ypp, src/parse/scanner.h
Before the change parsers relied on `YYSTYPE` global variable.
Not very handy for libre2c if it's expected to be used in reentrant
or multi-threaded contexts.
The change enables `%define api.pure full` and adjusts lexer calls
to explicitly pass through `YYSTYPE` around.
`%define api.pure full` is preferred to `%pure-parser` (deprecated in
2008, around Bison 2.3b). Should be safe to use.
=> bison parsers: switch to pure bison API

bootstrap/lib/parse.cc, bootstrap/src/parse/parser.cc, lib/parse.ypp, src/parse/parser.ypp
Unused exported symbols are detected by uselex:
yyerror: [R]: exported from: src/parse/re2go-parser.o src/parse/parser.o src/parse/re2rust-parser.o
yylex: [R]: exported from: src/parse/re2go-parser.o src/parse/parser.o src/parse/re2rust-parser.o
=> bison parsers: mark static yylex() and yyerror()

src/util/check.h
Without the change on `gcc-13` build warns as:
./src/parse/input.h: In member function 're2c::loc_t re2c::Input::cur_loc() const':
./src/parse/input.h:139:20: warning: unused variable 'p' [-Wunused-variable]
139 |     const uint8_t* p = cur;
|                    ^
The change turns `DCHECK(x)` into a statement that uses `x`.
=> src/util/check.h: always use DCHECK(x) argument to avoid warnings

BUILD.md, CONTRIBUTING.md
- In addition to a C++ compiler, Windows builds require a build system (CMake or bash). Clarify the dependencies to say this.
- Update docs rebuild dependencies to specify Python3 and Docutils, since that is what you need to install to make rst2man available.
- Add an explanation of how to use the presets since they're pretty good.
- A few other minor corrections.
=> BUILD.md - update dependencies, info about cmake presets

src/codegen/pass2_generate.cc, src/codegen/pass4_render.cc, src/constants.h, src/options/opt.cc, src/options/parse_opts.re, test/golang/006_error_default_api.go, test/golang/007_error_default_api.go, test/golang/010_error_case_ranges.go
Currently builds and passes every test with run_tests.py except: `golang/010_error_case_ranges.re`. One of the main differences from Go/Rust is that D supports case ranges like C. It also supports generic `enum`s which are just compile time constants which can be used basically like a C define macro. So far from converting the example programs the codegen seems to be working well.  I mostly just grepped for any use of `Lang::` and copied the existing code and made the smallest modifications I could to have it generate valid D code.
=> Introduce Dlang codegen.  

bazel/re2c.bzl
Mainly `[err_file]` is an undefined variable. My buildifier also put some random white spaces, I hope it's okay.
Probably some tl&c would be worth it, converting to bazel module, but that's for another day.
=> [bazel] Fix re2c_gen rule: remove a reference to an undefined variable

CMakeLists.txt
This simplifies the find_package() call. The version in find_package() has been initially supported in CMake 2 and 3. Version ranges (versionMin...[<]versionMax), on the other hand, are only supported by CMake 3.19+.
And this also helps a bit when adding re2c as a FetchContent dependency in CMake project where finding Python is not necessary and can be disabled with CMAKE_DISABLE_FIND_PACKAGE_Python3 variable.
=> Use Python version in find_package()

CMakeLists.txt
Hello. The re2c package requires python for docs and testing.
If the test targets can be disabled, the requirement of python can be dropped as well.
This introduces the flag `RE2C_BUILD_TESTS` for this purpose.
The deeper purpose is to facilitate integration of re2c into vcpkg,
which trivializes access to re2c on a Windows development environment.
=> Flag to make python optional as build dependency

playground/index.html
Before this fix, if you follow a shared link, it works properly but the URL gets changed.
=> Playground: don't change URL when shared link is used

CMakeLists.txt
The CMAKE_POSITION_INDEPENDENT_CODE variable enables PIC when building objects, and the CheckPIESupported module provides a check_pie_supported() command, which enables position independent code for executables (PIE) at the link step. Without this module, for example, building at the link step in some cases might fail. For example, on Haiku.
=> CMake: Add CheckPIESupported
